### ISSUE TITLE
Unlock reader only when Vilares, Centeio, Eiras or Gil pass their card

### ISSUE THREAD

**Issue by G-Pereira** [nuieee/inventions_RFId_CheckIn#6]
Only allow reading upon leaders arrive. Because this has integration with the leds, maybe it is easier to do it on the sensor side

**Comment by lm-sousa** [comment]
Useless. The log will have everyone from x to y hours, so this is not needed.

**Comment by dominguesgm** [comment]
People shouldn't have to wait for the excom to arrive to swipe the card. They should swipe the card iff they are coming to the meeting, whether they are the first or last to arrive.
